# Generated by Django 5.1.3 on 2024-12-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
