# Generated by Django 5.1.3 on 2024-12-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
