# Generated by Django 5.1.3 on 2024-12-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transconnect', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$LhE324Wo9VX2CzAf6uTwdK$GOdkTNB6mK6Oa3zXJHpYV5u1vKknKFluau7QgiyZmsM=', max_length=300),
        ),
    ]
