# Generated by Django 5.1.3 on 2024-12-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transconnect', '0003_alter_order_order_time_alter_ride_ride_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
