# Generated by Django 5.1.3 on 2024-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transconnect', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='passengers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
