# Generated by Django 5.1.3 on 2024-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transconnect', '0002_agency_created_at_controlled_controlled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('book_time', models.DateTimeField()),
                ('speed', models.FloatField()),
                ('driver_name', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='destination',
            new_name='from_place',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_place',
            new_name='to_place',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
    ]
